cloud_archive/users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import reverse_lazy

from .forms import PasswordResetAsyncForm
from .views import (
    DeleteProfileView,
    RegisterView,
    UpdateProfileView,
    VerificationCheckpointView,
    VerifyUserAccountView,
)


app_name = 'users'

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^profile/$', UpdateProfileView.as_view(), name='edit-profile'),
    url(
        r'^profile/delete/$',
        DeleteProfileView.as_view(),
        name='delete-profile',
    ),
    url(
        r'^password/reset/$',
        PasswordResetView.as_view(
            form_class=PasswordResetAsyncForm,
            success_url=reverse_lazy('users:password-reset-done'),
            email_template_name='mail/password_reset_email.mjml',
            subject_template_name='mail/password_reset_subject.txt',
            html_email_template_name='mail/password_reset_email.mjml',
        ),
        name='password-reset',
    ),
    url(
        r'^password/reset/done/$',
        PasswordResetDoneView.as_view(),
        name='password-reset-done',
    ),
    url(
        r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('users:password-reset-complete'),
        ),
        name='password-reset-complete',
    ),
    url(
        r'^password/complete/$',
        PasswordResetCompleteView.as_view(),
        name='password-reset-complete',
    ),
    url(
        r'^verify/checkpoint/$',
        VerificationCheckpointView.as_view(),
        name='verification-checkpoint',
    ),
    url(
        r'^verify/(?P<token>[:\-\d\w]+)/$',
        VerifyUserAccountView.as_view(),
        name='verify-account',
    ),
]

cloud_archive/users/models.py
import hashlib

from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.core import signing
from django.utils.crypto import get_random_string


class User(AbstractBaseUser):
    USERNAME_FIELD = 'email'

    email = models.EmailField(null=False, blank=False, unique=True)
    first_name = models.CharField(max_length=255, null=False, blank=True)
    is_active = models.BooleanField(default=True)
    last_name = models.CharField(max_length=255, null=False, blank=True)
    date_joined = models.DateTimeField(
        auto_now_add=True, null=False, blank=False,
    )
    is_verified = models.BooleanField(default=False)
    verification_token = models.CharField(max_length=15)

    objects = BaseUserManager()

    @property
    def md5_email(self):
        return hashlib.md5(self.email.encode('utf-8')).hexdigest()

    def get_full_name(self):
        full_name = '{} {}'.format(self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        return self.first_name

    def get_signed_verification_token(self):
        return signing.dumps(self.verification_token)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.verification_token = get_random_string(length=15)
        return super().save(*args, **kwargs)

    def verify_user(self):
        self.is_verified = True
        self.verification_token = ''
        self.save(update_fields=('is_verified', 'verification_token'))

cloud_archive/templates/base.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <meta charset="UTF-8">
        <title>Cloud Archive Application</title>
        <link rel="stylesheet" href="{% static 'bootswatch/paper/bootstrap.min.css' %}" />
        <link rel="stylesheet" href="{% static 'angular-filemanager/dist/angular-filemanager.min.css' %}" />
        {% block static_block %}
        {% endblock %}
    </head>
    <body>
        {% block body_block %}
        {% endblock %}
    </body>
</html>

cloud_archive/templates/base_container.html
{% extends 'base.html' %}
{% load static %}


{% block static_block %}
    <link rel="stylesheet" href="{% static 'css/container.css' %}" />
{% endblock %}


{% block body_block %}
<div class="base-container">
    {% block container_block %}
    {% endblock %}
</div>
{% endblock %}

cloud_archive/templates/delete-profile.html
{% extends 'base.html' %}
{% load static %}


{% block static_block %}
    <link rel="stylesheet" href="{% static 'css/file-manager.css' %}" />
    <link rel="stylesheet" href="{% static 'css/edit-profile.css' %}" />
{% endblock %}


{% block body_block %}
    <div class="container">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <h4><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span> Last chance...</h4>
                <form action="" method="POST">
                    <div class="form-group">
                        Clicking "Delete" will permanently delete your account.
                    </div>
                    <div class="form-group">
                        <a class="btn btn-secondary" href="{% url 'storage:file-manager' %}">Cancel</a>
                        <button class="btn btn-danger" type="submit">Delete</button>
                    </div>
                </form>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>
{% endblock %}

cloud_archive/templates/edit-profile.html
{% extends 'base.html' %}
{% load static %}


{% block static_block %}
    <link rel="stylesheet" href="{% static 'css/file-manager.css' %}" />
    <link rel="stylesheet" href="{% static 'css/edit-profile.css' %}" />
{% endblock %}


{% block body_block %}
    <nav class="navbar navbar-inverse navbar-default">
        <div class="container-fluid">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="nav-link" href="{% url 'storage:file-manager' %}">
                        <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span> GO BACK
                    </a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'users:logout' %}">
                        <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> LOGOUT
                    </a>
                </li>
          </ul>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h4><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Change First/Last name</h4>
                <form action="" method="POST">
                    <div class="form-group">
                        <label for="id_first_name">First name:</label>
                        {{ form.first_name }}
                   </div>
                    <div class="form-group">
                        <label for="id_first_name">Last name:</label>
                        {{ form.last_name }}
                   </div>
                    <div>
                        <button class="btn" type="submit">Update</button>
                    </div>
                </form>
            </div>
            <div class="col-md-4">
                <h4><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Change password</h4>
                <form action="" method="POST">
                    <input type="hidden" name="password-form" />
                    <div class="form-group">
                        {{ password_form.old_password.errors }}
                        <label for="id_first_name">Old password:</label>
                        {{ password_form.old_password }}
                   </div>
                    {{ password_form.new_password1.errors }}
                    {{ password_form.new_password2.errors }}
                    <div class="form-group">
                        <label for="id_first_name">New password:</label>
                        {{ password_form.new_password1 }}
                   </div>
                    <div class="form-group">
                        <label for="id_first_name">Confirm password:</label>
                        {{ password_form.new_password2 }}
                   </div>
                    <div>
                        <button class="btn" type="submit">
                            Change password
                        </button>
                    </div>
                </form>
            </div>
            <div class="col-md-4">
                <h4><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Statistics</h4>
                <p>
                    Email: {{ email }}
                </p>
                <p>
                    Date joined: {{ joined }}
                </p>
                <p>
                    Total number of folders: {{ folders_num }}
                </p>
                <p>
                    Total number of files: {{ files_num }}
                </p>
                <a class="btn btn-danger" href="{% url 'users:delete-profile' %}">Delete profile</a>

            </div>
        </div>
    </div>
{% endblock %}