cloud_archive/users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import reverse_lazy

from .forms import PasswordResetAsyncForm
from .views import (
    DeleteProfileView,
    RegisterView,
    UpdateProfileView,
    VerificationCheckpointView,
    VerifyUserAccountView,
)


app_name = 'users'

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^profile/$', UpdateProfileView.as_view(), name='edit-profile'),
    url(
        r'^profile/delete/$',
        DeleteProfileView.as_view(),
        name='delete-profile',
    ),
    url(
        r'^password/reset/$',
        PasswordResetView.as_view(
            form_class=PasswordResetAsyncForm,
            success_url=reverse_lazy('users:password-reset-done'),
            email_template_name='mail/password_reset_email.mjml',
            subject_template_name='mail/password_reset_subject.txt',
            html_email_template_name='mail/password_reset_email.mjml',
        ),
        name='password-reset',
    ),
    url(
        r'^password/reset/done/$',
        PasswordResetDoneView.as_view(),
        name='password-reset-done',
    ),
    url(
        r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('users:password-reset-complete'),
        ),
        name='password-reset-complete',
    ),
    url(
        r'^password/complete/$',
        PasswordResetCompleteView.as_view(),
        name='password-reset-complete',
    ),
    url(
        r'^verify/checkpoint/$',
        VerificationCheckpointView.as_view(),
        name='verification-checkpoint',
    ),
    url(
        r'^verify/(?P<token>[:\-\d\w]+)/$',
        VerifyUserAccountView.as_view(),
        name='verify-account',
    ),
]

cloud_archive/templates/verification/bad_signature.html
{% extends 'base_container.html' %}


{% block container_block %}
<div class="form">
    <h3>
        Invalid email token!
    </h3>
    <p class="error">
        Please click the link in the latest email you were sent.
    </p>
</div>
{% endblock %}

cloud_archive/templates/verification/checkpoint.html
{% extends 'base_container.html' %}


{% block container_block %}
<div class="form">
    <h3>
        Please verify your email before using Cloud Archive.
    </h3>
    <p class="message">
        Email not sent? Click on the button below to re-send verification email.
    </p>
    <form action="{% url 'users:verification-checkpoint' %}" method="POST">
        {% csrf_token %}
        <button class="btn" type="submit">Resend Verification Email</button>
    </form>
    <p class="message">
        or update your <a href="{% url 'users:edit-profile' %}">profile settings</a>
    </p>
</div>
{% endblock %}

cloud_archive/templates/verification/confirm.html
{% extends 'base_container.html' %}


{% block container_block %}
<div class="form">
    <h3>
        You have successfully verified your email!
    </h3>
    <p class="message">
        You can now upload your files.
        {% if request.user.is_authenticated %}
            <a href="{% url 'storage:file-manager' %}">Upload your files...</a>
        {% else %}
            <a href="{% url 'users:login' %}">Log in.</a>
        {% endif %}
    </p>
</div>
{% endblock %}

cloud_archive/templates/verification/resend_email_confirm.html
{% extends 'base_container.html' %}


{% block container_block %}
<div class="form">
    <p>
        Verification email has been sent to {{ request.user.email }}.
    </p>
    <p class="message">
        Please check your inbox.
    </p>
</div>
{% endblock %}